name: test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - if: matrix.os == 'macOS-latest'
        run: |
          brew install colima docker docker-compose tree
          colima start
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

      - run: npm install -g @go-task/cli @tigrisdata/tigris-cli

      - name: Run tests
        run: |
          export TIGRIS_URL=localhost:8081
          export TIGRIS_LOG_LEVEL=debug
          export TIGRIS_TEMPLATES_PATH=.
          /bin/bash tests/tests.sh
